#include <GLFW/glfw3.h>
#include "ability-hand-rendering.h"

const struct key_lookup_entry key_lookup[NUM_GRIPKEYS] = {
	{GLFW_KEY_1, CHUCK_GRASP_CFG_IDX},
	{GLFW_KEY_2, CHUCK_OK_GRASP_CFG_IDX},
	{GLFW_KEY_3, PINCH_GRASP_CFG_IDX},
	{GLFW_KEY_4, POWER_GRASP_CFG_IDX},
	{GLFW_KEY_5, KEY_GRASP_CFG_IDX},
	{GLFW_KEY_6, HANDSHAKE_CFG_IDX},
	{GLFW_KEY_7, TRIGGER_CFG_IDX},
	{GLFW_KEY_8, POINT_GRASP_CFG_IDX},
	{GLFW_KEY_T, SIGN_OF_THE_HORNS_CFG_IDX},
	{GLFW_KEY_Y, RUDE_POINT_GRASP_CFG_IDX},
	{GLFW_KEY_U, MODE_SWITCH_CLOSE_CFG_IDX},
	{GLFW_KEY_I, UTILITY_GRASP_CFG_IDX},
};

